name: Run tests and mypy

on:
  push:
      branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:

  unit_tests:
    if: |
      github.event_name == 'push' || github.event_name == 'pull_request'
    name: Unit testing
    runs-on: ubuntu-latest
    container:
        image: seitzdom/pytorch-ubuntu:latest
    # strategy:
    #   matrix:
    #     python-version: ["3.9", "3.10"]
    steps:
        - name: Install hatch
          shell: bash
          run: |
            apt-get update -y && apt-get install -y libglpk-dev glpk-utils git
            python -m pip install --upgrade pip
            python -m pip install hatch
            git --version
        - name: Set up Python
          uses: actions/setup-python@v2
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install main dependencies
          shell: bash
          run: |
            python -m hatch -v -e tests
        - name: Lint
          uses: pre-commit/action@v3.0.0

        - name: Perform unit tests
          shell: bash
          run: |
            python -m hatch -v -e tests run pytest -n auto && hatch -e docs run mkdocs build --clean --strict
